config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  # get 'welcome/index'
  resources :cryptocoins

  root to: 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cryptocoin.rb
class Cryptocoin < ApplicationRecord
  belongs_to :mining_type #, optional = true
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
  has_many :cryptocoins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    if params[:locale]
      cookies[:locale] = params[:locale]
    end

    if cookies[:locale]
      if I18n.locale != cookies[:locale]
        I18n.locale = cookies[:locale]
      end
    end
  end
end

app/controllers/cryptocoins_controller.rb
class CryptocoinsController < ApplicationController
  before_action :set_cryptocoin, only: [:show, :edit, :update, :destroy]
  before_action :set_mining_type_options, only: [:new, :edit]

  # GET /cryptocoins
  # GET /cryptocoins.json
  def index
    @cryptocoins = Cryptocoin.all
  end

  # GET /cryptocoins/1
  # GET /cryptocoins/1.json
  def show
  end

  # GET /cryptocoins/new
  def new
    @cryptocoin = Cryptocoin.new
  end

  # GET /cryptocoins/1/edit
  def edit
  end

  # POST /cryptocoins
  # POST /cryptocoins.json
  def create
    @cryptocoin = Cryptocoin.new(cryptocoin_params)

    respond_to do |format|
      if @cryptocoin.save
        format.html { redirect_to @cryptocoin, notice: 'Cryptocoin was successfully created.' }
        format.json { render :show, status: :created, location: @cryptocoin }
      else
        format.html { render :new }
        format.json { render json: @cryptocoin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptocoins/1
  # PATCH/PUT /cryptocoins/1.json
  def update
    respond_to do |format|
      if @cryptocoin.update(cryptocoin_params)
        format.html { redirect_to @cryptocoin, notice: 'Cryptocoin was successfully updated.' }
        format.json { render :show, status: :ok, location: @cryptocoin }
      else
        format.html { render :edit }
        format.json { render json: @cryptocoin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptocoins/1
  # DELETE /cryptocoins/1.json
  def destroy
    @cryptocoin.destroy
    respond_to do |format|
      format.html { redirect_to cryptocoins_url, notice: 'Cryptocoin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cryptocoin
      @cryptocoin = Cryptocoin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cryptocoin_params
      params.require(:cryptocoin).permit(:description, :acronym, :image_url, :mining_type_id)
    end

    def set_mining_type_options
      @mining_type_options = MiningType.all.pluck(:description, :id)
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: [:show, :edit, :update, :destroy]

  # GET /mining_types
  # GET /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1
  # GET /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types
  # POST /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to @mining_type, notice: 'Mining type was successfully created.' }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1
  # PATCH/PUT /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to @mining_type, notice: 'Mining type was successfully updated.' }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1
  # DELETE /mining_types/1.json
  def destroy
    @mining_type.destroy
    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: 'Mining type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @name = params[:name]
    if @name
      cookies[:name] = @name
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def br_date(date)
    return date.strftime("%d/%m/%Y")
  end
end

app/helpers/cryptocoins_helper.rb
module CryptocoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cryptocoins/_form.html.erb
<%= form_with(model: cryptocoin) do |form| %>
  <% if cryptocoin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cryptocoin.errors.count, "error") %> prohibited this cryptocoin from being saved:</h2>

      <ul>
        <% cryptocoin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :description, class: 'form-label' %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :acronym, class: 'form-label' %>
    <%= form.text_field :acronym, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :image_url, class: 'form-label' %>
    <%= form.text_field :image_url, class: 'form-control' %>
  </div>

  <div class="form-select">
    <%= form.label :mining_type_id, class: 'form-label' %>
    <%= form.select "mining_type_id", @mining_type_options, {include_blank: "Select one..."}, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit nil, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/cryptocoins/edit.html.erb
<h1>Editing Cryptocoin</h1>

<%= render 'form', cryptocoin: @cryptocoin %>

<%= link_to t('links.show'), @cryptocoin %> |
<%= link_to 'Back', cryptocoins_path %>

app/views/cryptocoins/index.html.erb
<p id="notice"><%= notice %></p>

<h1> <%= Cryptocoin.model_name.human(count: @cryptocoins.count) %> </h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= @cryptocoins.human_attribute_name(:image_url) %></th>
      <th><%= @cryptocoins.human_attribute_name(:description) %></th>
      <th><%= @cryptocoins.human_attribute_name(:acronym) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cryptocoins.each do |cryptocoin| %>
      <tr>
        <td><%= image_tag cryptocoin.image_url, width: 25, height: 25 %></td>
        <td><%= cryptocoin.description %></td>
        <td><%= cryptocoin.acronym %></td>
        <td><%= link_to t('links.show'), cryptocoin %></td>
        <td><%= link_to t('links.edit'), edit_cryptocoin_path(cryptocoin) %></td>
        <td><%= link_to t('links.destroy'), cryptocoin, method: :delete, data: { confirm: t('alerts.are_you_sure') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('links.new'), new_cryptocoin_path, class: 'btn btn-primary' %>

app/views/cryptocoins/new.html.erb
<h1>New Cryptocoin</h1>

<%= render 'form', cryptocoin: @cryptocoin %>

<%= link_to 'Back', cryptocoins_path %>

app/views/cryptocoins/show.html.erb
<p id="notice"><%= notice %></p>


<form >

  <div class="form-group">
    <%= label_tag @cryptocoin.class.human_attribute_name(:description) %>
    <%= text_field_tag nil, @cryptocoin.description, class: 'form-control', disabled: true %>
  </div>

  <div class="form-group">
    <%= label_tag @cryptocoin.class.human_attribute_name(:acronym) %>
    <%= text_field_tag nil, @cryptocoin.acronym, class: 'form-control', disabled: true %>
  </div>

  <div class="form-group">
    <%= label_tag @cryptocoin.class.human_attribute_name(:image_url) %>
    <%= text_field_tag nil, @cryptocoin.image_url, class: 'form-control', disabled: true %>
  </div>

  <div class="form-group">
    <%= label_tag @cryptocoin.class.human_attribute_name(:mining_type) %>
    <%= text_field_tag nil, @cryptocoin.mining_type.description, class: 'form-control', disabled: true %>
  </div>
</form>

<%= link_to 'Edit', edit_cryptocoin_path(@cryptocoin) %> |
<%= link_to 'Back', cryptocoins_path %>

app/views/cyptocoins/_form.html.erb
<%= form_with(model: cyptocoin) do |form| %>
  <% if cyptocoin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cyptocoin.errors.count, "error") %> prohibited this cyptocoin from being saved:</h2>

      <ul>
        <% cyptocoin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :acronym %>
    <%= form.text_field :acronym %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>CABEÇALHO - ADMIN</h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>    
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://rawgit.com/notifyjs/notifyjs/master/dist/notify.js"></script>
  </head>

  <body>
    <div class="container-fluid">
      
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <%= link_to "Português", root_path(locale: 'pt-BR'), class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "English", root_path(locale: 'en'), class: 'nav-link' %>
        </li>
      </ul>

      <%= yield %>
    </div>
  </body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type) do |form| %>
  <% if mining_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
        <% mining_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :acronym %>
    <%= form.text_field :acronym %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mining_types/edit.html.erb
<h1>Editing Mining Type</h1>

<%= render 'form', mining_type: @mining_type %>

<%= link_to 'Show', @mining_type %> |
<%= link_to 'Back', mining_types_path %>

app/views/mining_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= MiningType.model_name.human(count: @mining_types.count) %></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= @mining_types.human_attribute_name(:description) %></th>
      <th><%= @mining_types.human_attribute_name(:acronym) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mining_types.each do |mining_type| %>
      <tr>
        <td><%= mining_type.description %></td>
        <td><%= mining_type.acronym %></td>
        <td><%= link_to t('links.show'), mining_type %></td>
        <td><%= link_to t('links.edit'), edit_mining_type_path(mining_type) %></td>
        <td><%= link_to t('links.destroy'), mining_type, method: :delete, data: { confirm: t('are_you_sure') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('links.new'), new_mining_type_path, class: 'btn btn-primary' %>

app/views/mining_types/new.html.erb
<h1>New Mining Type</h1>

<%= render 'form', mining_type: @mining_type %>

<%= link_to 'Back', mining_types_path %>

app/views/mining_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @mining_type.description %>
</p>

<p>
  <strong>Acronym:</strong>
  <%= @mining_type.acronym %>
</p>

<%= link_to t('edit'), edit_mining_type_path(@mining_type) %> |
<%= link_to 'Back', mining_types_path %>

app/views/welcome/_menu.html.erb
<%= link_to Cryptocoin.model_name.human, cryptocoins_path, class: "btn btn-primary btn-lg", role: "button" %>
<%= link_to MiningType.model_name.human, mining_types_path, class: "btn btn-primary btn-lg", role: "button" %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4"> <%= "#{t(:welcome)}!" %> </h1>
  <p class="lead"> <%= "#{t(:about)}" %> </p>
  <hr class="my-4">
  <p>Idioma atual: <strong><%= t(:actual_locale) %></strong> </p>
  <p><strong>Data: </strong> <%= l(Date.today) %></p>
  <p class="lead">
    <%= render "menu" %>
  </p>
</div>